name: Test dotnet-sonar-scanner

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  test-dotnet-sonar-scanner:
    #strategy:
    #  matrix:
    #    os: [ubuntu-latest, windows-latest, macos-latest]
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    name: use chill-viking/dotnet-sonar-scanner
    steps:
      - uses: actions/checkout@v3
        name: Checkout this repo to access action
        with:
          path: './action-repo'

      - uses: actions/checkout@v3
        name: Checkout chill-viking/github-actions-tests
        with:
          repository: chill-viking/github-actions-tests
          path: './test-repo'

      - uses: ./action-repo
        name: use composite action
        with:
          sonar-project-key: 'chill-viking-org_github-actions-tests-dotnet-sonar-scanner'
          sonar-org-key: 'chill-viking-org'
          token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.ORG_SONAR_TOKEN }}
          project-version: '1.0.0-beta'
          working-directory: './test-repo/dotnet-sonar-scanner'
          checkout: false
