name: Test dotnet-sonar-scanner

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  test-dotnet-sonar-scanner:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: $
    name: use chill-viking/dotnet-sonar-scanner
    steps:
      - uses: actions/checkout@v3
        name: Checkout chill-viking/github-actions-tests
        with:
          name: chill-viking/github-actions-tests
          ref: refs/head/release

      - uses: ../../
        name: use composite action
        with:
          sonar-project-key: 'chill-viking-org_github-actions-tests-dotnet-sonar-scanner'
          sonar-org-key: 'chill-viking-org'
          token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN_DOTNET }}
          project-version: '1.0.0-beta'
          working-directory: './dotnet-sonar-scanner'
          checkout: false
